language: python

dist: focal

python:
  - '3.8'

install:
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_script:
  - psql -c "create database socialnetwork;" -U travis -p 5433
  - psql -c "create user myuser with encrypted password 'pass';" -U travis -p 5433
  - psql -c "grant all privileges on database socialnetwork to myuser;" -U travis -p 5433
  - psql -c "alter user myuser CREATEDB;" -U travis -p 5433

env:
  global:
    - PGPORT=5453
    - PGUSER=travis

script:
  - flake8 socialnetwork
  - cd network
  - coverage run --source='.' manage.py test

after_succes:
  - codecov
